import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  Workflow,
  Thermometer,
  ArrowUp,
  ArrowDown,
  Cloud,
  Leaf,
  Store,
  Calculator,
  Newspaper,
  MessageCircle,
  Users,
  X,
  ShoppingCart
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  thermometer: Thermometer,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  sun: Sun,
  user: User,
  cloud: Cloud,
  leaf: Leaf,
  store: Store,
  calculator: Calculator,
  newspaper: Newspaper,
  forum: MessageCircle,
  community: Users,
  cart: ShoppingCart
};

export { Icons };
